/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        store: {
            name: 'Store', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                    isOptional: true,
                }, timezone: {
                    name: "timezone",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "Asia/Shanghai" }] }],
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "USD" }] }],
                }, active: {
                    name: "active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, users: {
                    name: "users",
                    type: "StoreUser",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, categories: {
                    name: "categories",
                    type: "Category",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, products: {
                    name: "products",
                    type: "Product",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, orders: {
                    name: "orders",
                    type: "Order",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, refunds: {
                    name: "refunds",
                    type: "Refund",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, auditLogs: {
                    name: "auditLogs",
                    type: "OrderAuditLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, shifts: {
                    name: "shifts",
                    type: "Shift",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, cashMovements: {
                    name: "cashMovements",
                    type: "CashMovement",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, kitchenStations: {
                    name: "kitchenStations",
                    type: "KitchenStation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, kitchenTickets: {
                    name: "kitchenTickets",
                    type: "KitchenTicket",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, kitchenTicketItems: {
                    name: "kitchenTicketItems",
                    type: "KitchenTicketItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, printers: {
                    name: "printers",
                    type: "Printer",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, printerRoutes: {
                    name: "printerRoutes",
                    type: "PrinterRoute",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, printJobs: {
                    name: "printJobs",
                    type: "PrintJob",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, aiDrafts: {
                    name: "aiDrafts",
                    type: "AiDraft",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, campaigns: {
                    name: "campaigns",
                    type: "Campaign",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            },
        },
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, email: {
                    name: "email",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                    isOptional: true,
                }, passwordHash: {
                    name: "passwordHash",
                    type: "String",
                }, active: {
                    name: "active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, stores: {
                    name: "stores",
                    type: "StoreUser",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, operatedRefunds: {
                    name: "operatedRefunds",
                    type: "Refund",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'operator',
                }, approvedRefunds: {
                    name: "approvedRefunds",
                    type: "Refund",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'approvedBy',
                }, operatedOrderAuditLogs: {
                    name: "operatedOrderAuditLogs",
                    type: "OrderAuditLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'operator',
                }, approvedOrderAuditLogs: {
                    name: "approvedOrderAuditLogs",
                    type: "OrderAuditLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'approvedBy',
                }, shifts: {
                    name: "shifts",
                    type: "Shift",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, openedShifts: {
                    name: "openedShifts",
                    type: "Shift",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'openedBy',
                }, closedShifts: {
                    name: "closedShifts",
                    type: "Shift",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'closedBy',
                }, cashMovements: {
                    name: "cashMovements",
                    type: "CashMovement",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, createdKitchenTickets: {
                    name: "createdKitchenTickets",
                    type: "KitchenTicket",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, requestedPrintJobs: {
                    name: "requestedPrintJobs",
                    type: "PrintJob",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'requestedBy',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        storeUser: {
            name: 'StoreUser', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'users',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'stores',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, role: {
                    name: "role",
                    type: "StoreRole",
                }, active: {
                    name: "active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_userId: {
                    name: "storeId_userId",
                    fields: ["storeId", "userId"]
                },
            },
        },
        category: {
            name: 'Category', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'categories',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "CatalogStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sortOrder: {
                    name: "sortOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, defaultKitchenStationId: {
                    name: "defaultKitchenStationId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'defaultKitchenStation',
                }, defaultKitchenStation: {
                    name: "defaultKitchenStation",
                    type: "KitchenStation",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'categories',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "defaultKitchenStationId" },
                }, products: {
                    name: "products",
                    type: "Product",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'categoryRef',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_name: {
                    name: "storeId_name",
                    fields: ["storeId", "name"]
                },
            },
        },
        product: {
            name: 'Product', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'products',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'categoryRef',
                }, categoryRef: {
                    name: "categoryRef",
                    type: "Category",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'products',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "categoryId" },
                }, category: {
                    name: "category",
                    type: "String",
                    isOptional: true,
                }, price: {
                    name: "price",
                    type: "Decimal",
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "USD" }] }],
                }, isActive: {
                    name: "isActive",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, availabilityStatus: {
                    name: "availabilityStatus",
                    type: "ProductAvailabilityStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, kitchenStationId: {
                    name: "kitchenStationId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'kitchenStation',
                }, kitchenStation: {
                    name: "kitchenStation",
                    type: "KitchenStation",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'products',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "kitchenStationId" },
                }, modifierGroups: {
                    name: "modifierGroups",
                    type: "ProductModifierGroup",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                }, orderItems: {
                    name: "orderItems",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        productModifierGroup: {
            name: 'ProductModifierGroup', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, productId: {
                    name: "productId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'product',
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'modifierGroups',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, required: {
                    name: "required",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, multiSelect: {
                    name: "multiSelect",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, minSelect: {
                    name: "minSelect",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, maxSelect: {
                    name: "maxSelect",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 1 }] }],
                }, status: {
                    name: "status",
                    type: "CatalogStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, displayOrder: {
                    name: "displayOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, options: {
                    name: "options",
                    type: "ProductModifierOption",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'group',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        productModifierOption: {
            name: 'ProductModifierOption', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, groupId: {
                    name: "groupId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'group',
                }, group: {
                    name: "group",
                    type: "ProductModifierGroup",
                    isDataModel: true,
                    backLink: 'options',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "groupId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, priceDelta: {
                    name: "priceDelta",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, status: {
                    name: "status",
                    type: "ModifierOptionStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, displayOrder: {
                    name: "displayOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        order: {
            name: 'Order', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, orderNumber: {
                    name: "orderNumber",
                    type: "String",
                }, pickupNumber: {
                    name: "pickupNumber",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "OrderStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, printStatus: {
                    name: "printStatus",
                    type: "PrintStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, paymentMethod: {
                    name: "paymentMethod",
                    type: "PaymentMethod",
                    isOptional: true,
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "USD" }] }],
                }, subtotal: {
                    name: "subtotal",
                    type: "Decimal",
                }, adjustment: {
                    name: "adjustment",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, adjustmentType: {
                    name: "adjustmentType",
                    type: "String",
                    isOptional: true,
                }, adjustmentValue: {
                    name: "adjustmentValue",
                    type: "Decimal",
                    isOptional: true,
                }, tax: {
                    name: "tax",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, tip: {
                    name: "tip",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, total: {
                    name: "total",
                    type: "Decimal",
                }, cashReceived: {
                    name: "cashReceived",
                    type: "Decimal",
                    isOptional: true,
                }, changeDue: {
                    name: "changeDue",
                    type: "Decimal",
                    isOptional: true,
                }, paidAt: {
                    name: "paidAt",
                    type: "DateTime",
                    isOptional: true,
                }, printedAt: {
                    name: "printedAt",
                    type: "DateTime",
                    isOptional: true,
                }, items: {
                    name: "items",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, payments: {
                    name: "payments",
                    type: "OrderPayment",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, refunds: {
                    name: "refunds",
                    type: "Refund",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, auditLogs: {
                    name: "auditLogs",
                    type: "OrderAuditLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, kitchenTickets: {
                    name: "kitchenTickets",
                    type: "KitchenTicket",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, orderNumber: {
                    name: "orderNumber",
                    fields: ["orderNumber"]
                },
            },
        },
        orderPayment: {
            name: 'OrderPayment', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'payments',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, method: {
                    name: "method",
                    type: "PaymentMethod",
                }, amount: {
                    name: "amount",
                    type: "Decimal",
                }, amountReceived: {
                    name: "amountReceived",
                    type: "Decimal",
                    isOptional: true,
                }, changeDue: {
                    name: "changeDue",
                    type: "Decimal",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        orderItem: {
            name: 'OrderItem', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'items',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, productId: {
                    name: "productId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'product',
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'orderItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                }, productNameSnapshot: {
                    name: "productNameSnapshot",
                    type: "String",
                    isOptional: true,
                }, productCategorySnapshot: {
                    name: "productCategorySnapshot",
                    type: "String",
                    isOptional: true,
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                }, unitPrice: {
                    name: "unitPrice",
                    type: "Decimal",
                }, lineTotal: {
                    name: "lineTotal",
                    type: "Decimal",
                }, modifiers: {
                    name: "modifiers",
                    type: "Json",
                    isOptional: true,
                }, refundItems: {
                    name: "refundItems",
                    type: "RefundItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'orderItem',
                }, kitchenTicketItems: {
                    name: "kitchenTicketItems",
                    type: "KitchenTicketItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'orderItem',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        refund: {
            name: 'Refund', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'refunds',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'refunds',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, refundNumber: {
                    name: "refundNumber",
                    type: "String",
                }, idempotencyKey: {
                    name: "idempotencyKey",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "RefundStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, method: {
                    name: "method",
                    type: "PaymentMethod",
                }, amount: {
                    name: "amount",
                    type: "Decimal",
                }, reason: {
                    name: "reason",
                    type: "String",
                }, operatorId: {
                    name: "operatorId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'operator',
                }, operator: {
                    name: "operator",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'operatedRefunds',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "operatorId" },
                }, approvedById: {
                    name: "approvedById",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'approvedBy',
                }, approvedBy: {
                    name: "approvedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'approvedRefunds',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "approvedById" },
                }, items: {
                    name: "items",
                    type: "RefundItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'refund',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, refundNumber: {
                    name: "refundNumber",
                    fields: ["refundNumber"]
                }, storeId_idempotencyKey: {
                    name: "storeId_idempotencyKey",
                    fields: ["storeId", "idempotencyKey"]
                },
            },
        },
        refundItem: {
            name: 'RefundItem', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, refundId: {
                    name: "refundId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'refund',
                }, refund: {
                    name: "refund",
                    type: "Refund",
                    isDataModel: true,
                    backLink: 'items',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "refundId" },
                }, orderItemId: {
                    name: "orderItemId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'orderItem',
                }, orderItem: {
                    name: "orderItem",
                    type: "OrderItem",
                    isDataModel: true,
                    backLink: 'refundItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderItemId" },
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                }, amount: {
                    name: "amount",
                    type: "Decimal",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        orderAuditLog: {
            name: 'OrderAuditLog', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'auditLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'auditLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, action: {
                    name: "action",
                    type: "OrderAuditAction",
                }, fromStatus: {
                    name: "fromStatus",
                    type: "OrderStatus",
                    isOptional: true,
                }, toStatus: {
                    name: "toStatus",
                    type: "OrderStatus",
                    isOptional: true,
                }, amount: {
                    name: "amount",
                    type: "Decimal",
                    isOptional: true,
                }, reason: {
                    name: "reason",
                    type: "String",
                }, operatorId: {
                    name: "operatorId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'operator',
                }, operator: {
                    name: "operator",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'operatedOrderAuditLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "operatorId" },
                }, approvedById: {
                    name: "approvedById",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'approvedBy',
                }, approvedBy: {
                    name: "approvedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'approvedOrderAuditLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "approvedById" },
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        shift: {
            name: 'Shift', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'shifts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'shifts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, status: {
                    name: "status",
                    type: "ShiftStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, openedAt: {
                    name: "openedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, closedAt: {
                    name: "closedAt",
                    type: "DateTime",
                    isOptional: true,
                }, openingCash: {
                    name: "openingCash",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, expectedCash: {
                    name: "expectedCash",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, actualCash: {
                    name: "actualCash",
                    type: "Decimal",
                    isOptional: true,
                }, variance: {
                    name: "variance",
                    type: "Decimal",
                    isOptional: true,
                }, openedByUserId: {
                    name: "openedByUserId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'openedBy',
                }, openedBy: {
                    name: "openedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'openedShifts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "openedByUserId" },
                }, closedByUserId: {
                    name: "closedByUserId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'closedBy',
                }, closedBy: {
                    name: "closedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'closedShifts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "closedByUserId" },
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, movements: {
                    name: "movements",
                    type: "CashMovement",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'shift',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        cashMovement: {
            name: 'CashMovement', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'cashMovements',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, shiftId: {
                    name: "shiftId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'shift',
                }, shift: {
                    name: "shift",
                    type: "Shift",
                    isDataModel: true,
                    backLink: 'movements',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "shiftId" },
                }, type: {
                    name: "type",
                    type: "CashMovementType",
                }, amount: {
                    name: "amount",
                    type: "Decimal",
                }, reason: {
                    name: "reason",
                    type: "String",
                }, referenceType: {
                    name: "referenceType",
                    type: "CashMovementReferenceType",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, referenceId: {
                    name: "referenceId",
                    type: "String",
                    isOptional: true,
                }, createdByUserId: {
                    name: "createdByUserId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'cashMovements',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "createdByUserId" },
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_type_referenceType_referenceId: {
                    name: "storeId_type_referenceType_referenceId",
                    fields: ["storeId", "type", "referenceType", "referenceId"]
                },
            },
        },
        kitchenStation: {
            name: 'KitchenStation', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'kitchenStations',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "KitchenStationStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sortOrder: {
                    name: "sortOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, isDefault: {
                    name: "isDefault",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, products: {
                    name: "products",
                    type: "Product",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'kitchenStation',
                }, categories: {
                    name: "categories",
                    type: "Category",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'defaultKitchenStation',
                }, tickets: {
                    name: "tickets",
                    type: "KitchenTicket",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'station',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_code: {
                    name: "storeId_code",
                    fields: ["storeId", "code"]
                },
            },
        },
        kitchenTicket: {
            name: 'KitchenTicket', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'kitchenTickets',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'kitchenTickets',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, stationId: {
                    name: "stationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'station',
                }, station: {
                    name: "station",
                    type: "KitchenStation",
                    isDataModel: true,
                    backLink: 'tickets',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "stationId" },
                }, ticketNumber: {
                    name: "ticketNumber",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "KitchenTicketStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, startedAt: {
                    name: "startedAt",
                    type: "DateTime",
                    isOptional: true,
                }, readyAt: {
                    name: "readyAt",
                    type: "DateTime",
                    isOptional: true,
                }, completedAt: {
                    name: "completedAt",
                    type: "DateTime",
                    isOptional: true,
                }, cancelledAt: {
                    name: "cancelledAt",
                    type: "DateTime",
                    isOptional: true,
                }, cancelReason: {
                    name: "cancelReason",
                    type: "String",
                    isOptional: true,
                }, createdByUserId: {
                    name: "createdByUserId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdKitchenTickets',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "createdByUserId" },
                }, items: {
                    name: "items",
                    type: "KitchenTicketItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'ticket',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, ticketNumber: {
                    name: "ticketNumber",
                    fields: ["ticketNumber"]
                }, storeId_orderId_stationId: {
                    name: "storeId_orderId_stationId",
                    fields: ["storeId", "orderId", "stationId"]
                },
            },
        },
        kitchenTicketItem: {
            name: 'KitchenTicketItem', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'kitchenTicketItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, ticketId: {
                    name: "ticketId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'ticket',
                }, ticket: {
                    name: "ticket",
                    type: "KitchenTicket",
                    isDataModel: true,
                    backLink: 'items',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "ticketId" },
                }, orderItemId: {
                    name: "orderItemId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'orderItem',
                }, orderItem: {
                    name: "orderItem",
                    type: "OrderItem",
                    isDataModel: true,
                    backLink: 'kitchenTicketItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderItemId" },
                }, productId: {
                    name: "productId",
                    type: "String",
                }, productNameSnapshot: {
                    name: "productNameSnapshot",
                    type: "String",
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                }, modifiers: {
                    name: "modifiers",
                    type: "Json",
                    isOptional: true,
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "KitchenTicketStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        printer: {
            name: 'Printer', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'printers',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                }, type: {
                    name: "type",
                    type: "PrinterType",
                }, connectionType: {
                    name: "connectionType",
                    type: "PrinterConnectionType",
                }, status: {
                    name: "status",
                    type: "PrinterStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, host: {
                    name: "host",
                    type: "String",
                    isOptional: true,
                }, port: {
                    name: "port",
                    type: "Int",
                    isOptional: true,
                }, usbVendorId: {
                    name: "usbVendorId",
                    type: "String",
                    isOptional: true,
                }, usbProductId: {
                    name: "usbProductId",
                    type: "String",
                    isOptional: true,
                }, paperWidth: {
                    name: "paperWidth",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 80 }] }],
                }, autoCut: {
                    name: "autoCut",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, cashDrawerPulse: {
                    name: "cashDrawerPulse",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, routes: {
                    name: "routes",
                    type: "PrinterRoute",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'printer',
                }, printJobs: {
                    name: "printJobs",
                    type: "PrintJob",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'printer',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_code: {
                    name: "storeId_code",
                    fields: ["storeId", "code"]
                },
            },
        },
        printerRoute: {
            name: 'PrinterRoute', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'printerRoutes',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, printerId: {
                    name: "printerId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'printer',
                }, printer: {
                    name: "printer",
                    type: "Printer",
                    isDataModel: true,
                    backLink: 'routes',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "printerId" },
                }, routeType: {
                    name: "routeType",
                    type: "PrinterRouteType",
                }, targetId: {
                    name: "targetId",
                    type: "String",
                    isOptional: true,
                }, documentType: {
                    name: "documentType",
                    type: "PrintDocumentType",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_routeType_targetId_documentType: {
                    name: "storeId_routeType_targetId_documentType",
                    fields: ["storeId", "routeType", "targetId", "documentType"]
                },
            },
        },
        printJob: {
            name: 'PrintJob', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'printJobs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, printerId: {
                    name: "printerId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'printer',
                }, printer: {
                    name: "printer",
                    type: "Printer",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'printJobs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "printerId" },
                }, documentType: {
                    name: "documentType",
                    type: "PrintDocumentType",
                }, referenceType: {
                    name: "referenceType",
                    type: "PrintJobReferenceType",
                }, referenceId: {
                    name: "referenceId",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "PrintJobStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, reason: {
                    name: "reason",
                    type: "PrintJobReason",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, payload: {
                    name: "payload",
                    type: "Json",
                }, renderedText: {
                    name: "renderedText",
                    type: "String",
                    isOptional: true,
                }, byteLength: {
                    name: "byteLength",
                    type: "Int",
                    isOptional: true,
                }, retryCount: {
                    name: "retryCount",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, maxRetries: {
                    name: "maxRetries",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 3 }] }],
                }, lastError: {
                    name: "lastError",
                    type: "String",
                    isOptional: true,
                }, autoPrintKey: {
                    name: "autoPrintKey",
                    type: "String",
                    isOptional: true,
                }, sourceJobId: {
                    name: "sourceJobId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'sourceJob',
                }, sourceJob: {
                    name: "sourceJob",
                    type: "PrintJob",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'reprints',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "sourceJobId" },
                }, reprints: {
                    name: "reprints",
                    type: "PrintJob",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'sourceJob',
                }, requestedByUserId: {
                    name: "requestedByUserId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'requestedBy',
                }, requestedBy: {
                    name: "requestedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'requestedPrintJobs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "requestedByUserId" },
                }, claimedByDeviceId: {
                    name: "claimedByDeviceId",
                    type: "String",
                    isOptional: true,
                }, startedAt: {
                    name: "startedAt",
                    type: "DateTime",
                    isOptional: true,
                }, completedAt: {
                    name: "completedAt",
                    type: "DateTime",
                    isOptional: true,
                }, nextRetryAt: {
                    name: "nextRetryAt",
                    type: "DateTime",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_documentType_referenceType_referenceId_autoPrintKey: {
                    name: "storeId_documentType_referenceType_referenceId_autoPrintKey",
                    fields: ["storeId", "documentType", "referenceType", "referenceId", "autoPrintKey"]
                },
            },
        },
        aiDraft: {
            name: 'AiDraft', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'aiDrafts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, prompt: {
                    name: "prompt",
                    type: "String",
                }, structuredJson: {
                    name: "structuredJson",
                    type: "Json",
                }, status: {
                    name: "status",
                    type: "AiDraftStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, confirmedAt: {
                    name: "confirmedAt",
                    type: "DateTime",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        campaign: {
            name: 'Campaign', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'campaigns',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, goal: {
                    name: "goal",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "CampaignStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, discountType: {
                    name: "discountType",
                    type: "String",
                    isOptional: true,
                }, discountValue: {
                    name: "discountValue",
                    type: "Float",
                    isOptional: true,
                }, timeWindow: {
                    name: "timeWindow",
                    type: "String",
                    isOptional: true,
                }, bannerCopy: {
                    name: "bannerCopy",
                    type: "String",
                    isOptional: true,
                }, staffMessage: {
                    name: "staffMessage",
                    type: "String",
                    isOptional: true,
                }, structuredJson: {
                    name: "structuredJson",
                    type: "Json",
                    isOptional: true,
                }, createdById: {
                    name: "createdById",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },

    },
    deleteCascade: {

    },
    authModel: 'User'

};
export default metadata;
