/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        store: {
            name: 'Store', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                    isOptional: true,
                }, timezone: {
                    name: "timezone",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "Asia/Shanghai" }] }],
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "USD" }] }],
                }, active: {
                    name: "active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, users: {
                    name: "users",
                    type: "StoreUser",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, categories: {
                    name: "categories",
                    type: "Category",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, products: {
                    name: "products",
                    type: "Product",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, orders: {
                    name: "orders",
                    type: "Order",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, aiDrafts: {
                    name: "aiDrafts",
                    type: "AiDraft",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, campaigns: {
                    name: "campaigns",
                    type: "Campaign",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'store',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            },
        },
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, email: {
                    name: "email",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                    isOptional: true,
                }, passwordHash: {
                    name: "passwordHash",
                    type: "String",
                }, active: {
                    name: "active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, stores: {
                    name: "stores",
                    type: "StoreUser",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        storeUser: {
            name: 'StoreUser', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'users',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'stores',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, role: {
                    name: "role",
                    type: "StoreRole",
                }, active: {
                    name: "active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_userId: {
                    name: "storeId_userId",
                    fields: ["storeId", "userId"]
                },
            },
        },
        category: {
            name: 'Category', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'categories',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "CatalogStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sortOrder: {
                    name: "sortOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, products: {
                    name: "products",
                    type: "Product",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'categoryRef',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, storeId_name: {
                    name: "storeId_name",
                    fields: ["storeId", "name"]
                },
            },
        },
        product: {
            name: 'Product', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'products',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'categoryRef',
                }, categoryRef: {
                    name: "categoryRef",
                    type: "Category",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'products',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "categoryId" },
                }, category: {
                    name: "category",
                    type: "String",
                    isOptional: true,
                }, price: {
                    name: "price",
                    type: "Decimal",
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "USD" }] }],
                }, isActive: {
                    name: "isActive",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, availabilityStatus: {
                    name: "availabilityStatus",
                    type: "ProductAvailabilityStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, modifierGroups: {
                    name: "modifierGroups",
                    type: "ProductModifierGroup",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                }, orderItems: {
                    name: "orderItems",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        productModifierGroup: {
            name: 'ProductModifierGroup', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, productId: {
                    name: "productId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'product',
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'modifierGroups',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, required: {
                    name: "required",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, multiSelect: {
                    name: "multiSelect",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, minSelect: {
                    name: "minSelect",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, maxSelect: {
                    name: "maxSelect",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 1 }] }],
                }, status: {
                    name: "status",
                    type: "CatalogStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, displayOrder: {
                    name: "displayOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, options: {
                    name: "options",
                    type: "ProductModifierOption",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'group',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        productModifierOption: {
            name: 'ProductModifierOption', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, groupId: {
                    name: "groupId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'group',
                }, group: {
                    name: "group",
                    type: "ProductModifierGroup",
                    isDataModel: true,
                    backLink: 'options',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "groupId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, priceDelta: {
                    name: "priceDelta",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, status: {
                    name: "status",
                    type: "ModifierOptionStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, displayOrder: {
                    name: "displayOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        order: {
            name: 'Order', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, orderNumber: {
                    name: "orderNumber",
                    type: "String",
                }, pickupNumber: {
                    name: "pickupNumber",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "OrderStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, printStatus: {
                    name: "printStatus",
                    type: "PrintStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, paymentMethod: {
                    name: "paymentMethod",
                    type: "PaymentMethod",
                    isOptional: true,
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "USD" }] }],
                }, subtotal: {
                    name: "subtotal",
                    type: "Decimal",
                }, adjustment: {
                    name: "adjustment",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, adjustmentType: {
                    name: "adjustmentType",
                    type: "String",
                    isOptional: true,
                }, adjustmentValue: {
                    name: "adjustmentValue",
                    type: "Decimal",
                    isOptional: true,
                }, tax: {
                    name: "tax",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, tip: {
                    name: "tip",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, total: {
                    name: "total",
                    type: "Decimal",
                }, cashReceived: {
                    name: "cashReceived",
                    type: "Decimal",
                    isOptional: true,
                }, changeDue: {
                    name: "changeDue",
                    type: "Decimal",
                    isOptional: true,
                }, paidAt: {
                    name: "paidAt",
                    type: "DateTime",
                    isOptional: true,
                }, printedAt: {
                    name: "printedAt",
                    type: "DateTime",
                    isOptional: true,
                }, items: {
                    name: "items",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, payments: {
                    name: "payments",
                    type: "OrderPayment",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, orderNumber: {
                    name: "orderNumber",
                    fields: ["orderNumber"]
                },
            },
        },
        orderPayment: {
            name: 'OrderPayment', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'payments',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, method: {
                    name: "method",
                    type: "PaymentMethod",
                }, amount: {
                    name: "amount",
                    type: "Decimal",
                }, amountReceived: {
                    name: "amountReceived",
                    type: "Decimal",
                    isOptional: true,
                }, changeDue: {
                    name: "changeDue",
                    type: "Decimal",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        orderItem: {
            name: 'OrderItem', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'items',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, productId: {
                    name: "productId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'product',
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'orderItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                }, productNameSnapshot: {
                    name: "productNameSnapshot",
                    type: "String",
                    isOptional: true,
                }, productCategorySnapshot: {
                    name: "productCategorySnapshot",
                    type: "String",
                    isOptional: true,
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                }, unitPrice: {
                    name: "unitPrice",
                    type: "Decimal",
                }, lineTotal: {
                    name: "lineTotal",
                    type: "Decimal",
                }, modifiers: {
                    name: "modifiers",
                    type: "Json",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        aiDraft: {
            name: 'AiDraft', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'aiDrafts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, prompt: {
                    name: "prompt",
                    type: "String",
                }, structuredJson: {
                    name: "structuredJson",
                    type: "Json",
                }, status: {
                    name: "status",
                    type: "AiDraftStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, confirmedAt: {
                    name: "confirmedAt",
                    type: "DateTime",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        campaign: {
            name: 'Campaign', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storeId: {
                    name: "storeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'store',
                }, store: {
                    name: "store",
                    type: "Store",
                    isDataModel: true,
                    backLink: 'campaigns',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "storeId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, goal: {
                    name: "goal",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "CampaignStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, discountType: {
                    name: "discountType",
                    type: "String",
                    isOptional: true,
                }, discountValue: {
                    name: "discountValue",
                    type: "Float",
                    isOptional: true,
                }, timeWindow: {
                    name: "timeWindow",
                    type: "String",
                    isOptional: true,
                }, bannerCopy: {
                    name: "bannerCopy",
                    type: "String",
                    isOptional: true,
                }, staffMessage: {
                    name: "staffMessage",
                    type: "String",
                    isOptional: true,
                }, structuredJson: {
                    name: "structuredJson",
                    type: "Json",
                    isOptional: true,
                }, createdById: {
                    name: "createdById",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },

    },
    deleteCascade: {

    },
    authModel: 'User'

};
export default metadata;
