/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, AiDraft } from "./__types";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateAiDraft(options?: Omit<(UseMutationOptions<(AiDraft | undefined), DefaultError, Prisma.AiDraftCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AiDraftCreateArgs, DefaultError, AiDraft, true>('AiDraft', 'POST', `${endpoint}/aiDraft/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AiDraftCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.AiDraftCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, AiDraft, Prisma.AiDraftGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.AiDraftCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, AiDraft, Prisma.AiDraftGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyAiDraft(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AiDraftCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AiDraftCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('AiDraft', 'POST', `${endpoint}/aiDraft/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AiDraftCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.AiDraftCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AiDraftCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyAiDraft<TArgs extends Prisma.AiDraftFindManyArgs, TQueryFnData = Array<Prisma.AiDraftGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AiDraftFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/findMany`, args, options, fetch);
}

export function useInfiniteFindManyAiDraft<TArgs extends Prisma.AiDraftFindManyArgs, TQueryFnData = Array<Prisma.AiDraftGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AiDraftFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/findMany`, args, options, fetch);
}

export function useSuspenseFindManyAiDraft<TArgs extends Prisma.AiDraftFindManyArgs, TQueryFnData = Array<Prisma.AiDraftGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AiDraftFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyAiDraft<TArgs extends Prisma.AiDraftFindManyArgs, TQueryFnData = Array<Prisma.AiDraftGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AiDraftFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/findMany`, args, options, fetch);
}

export function useFindUniqueAiDraft<TArgs extends Prisma.AiDraftFindUniqueArgs, TQueryFnData = Prisma.AiDraftGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.AiDraftFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueAiDraft<TArgs extends Prisma.AiDraftFindUniqueArgs, TQueryFnData = Prisma.AiDraftGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.AiDraftFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/findUnique`, args, options, fetch);
}

export function useFindFirstAiDraft<TArgs extends Prisma.AiDraftFindFirstArgs, TQueryFnData = Prisma.AiDraftGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AiDraftFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstAiDraft<TArgs extends Prisma.AiDraftFindFirstArgs, TQueryFnData = Prisma.AiDraftGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AiDraftFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/findFirst`, args, options, fetch);
}

export function useUpdateAiDraft(options?: Omit<(UseMutationOptions<(AiDraft | undefined), DefaultError, Prisma.AiDraftUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AiDraftUpdateArgs, DefaultError, AiDraft, true>('AiDraft', 'PUT', `${endpoint}/aiDraft/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AiDraftUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.AiDraftUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, AiDraft, Prisma.AiDraftGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.AiDraftUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, AiDraft, Prisma.AiDraftGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyAiDraft(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AiDraftUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AiDraftUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('AiDraft', 'PUT', `${endpoint}/aiDraft/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AiDraftUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.AiDraftUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AiDraftUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertAiDraft(options?: Omit<(UseMutationOptions<(AiDraft | undefined), DefaultError, Prisma.AiDraftUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AiDraftUpsertArgs, DefaultError, AiDraft, true>('AiDraft', 'POST', `${endpoint}/aiDraft/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AiDraftUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.AiDraftUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, AiDraft, Prisma.AiDraftGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.AiDraftUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, AiDraft, Prisma.AiDraftGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteAiDraft(options?: Omit<(UseMutationOptions<(AiDraft | undefined), DefaultError, Prisma.AiDraftDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AiDraftDeleteArgs, DefaultError, AiDraft, true>('AiDraft', 'DELETE', `${endpoint}/aiDraft/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AiDraftDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.AiDraftDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, AiDraft, Prisma.AiDraftGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.AiDraftDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, AiDraft, Prisma.AiDraftGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyAiDraft(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AiDraftDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AiDraftDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('AiDraft', 'DELETE', `${endpoint}/aiDraft/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AiDraftDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.AiDraftDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AiDraftDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateAiDraft<TArgs extends Prisma.AiDraftAggregateArgs, TQueryFnData = Prisma.GetAiDraftAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.AiDraftAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateAiDraft<TArgs extends Prisma.AiDraftAggregateArgs, TQueryFnData = Prisma.GetAiDraftAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.AiDraftAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/aggregate`, args, options, fetch);
}

export function useGroupByAiDraft<TArgs extends Prisma.AiDraftGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AiDraftGroupByArgs['orderBy'] } : { orderBy?: Prisma.AiDraftGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.AiDraftGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.AiDraftGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.AiDraftGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.AiDraftGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.AiDraftGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByAiDraft<TArgs extends Prisma.AiDraftGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AiDraftGroupByArgs['orderBy'] } : { orderBy?: Prisma.AiDraftGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.AiDraftGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.AiDraftGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.AiDraftGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.AiDraftGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.AiDraftGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/groupBy`, args, options, fetch);
}

export function useCountAiDraft<TArgs extends Prisma.AiDraftCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.AiDraftCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AiDraftCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/count`, args, options, fetch);
}

export function useSuspenseCountAiDraft<TArgs extends Prisma.AiDraftCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.AiDraftCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AiDraftCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AiDraft', `${endpoint}/aiDraft/count`, args, options, fetch);
}
import type { AiDraftStatus } from './__types';

export function useCheckAiDraft<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; prompt?: string; status?: AiDraftStatus }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('AiDraft', `${endpoint}/aiDraft/check`, args, options, fetch);
}
