/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, KitchenTicketItem } from "./__types";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateKitchenTicketItem(options?: Omit<(UseMutationOptions<(KitchenTicketItem | undefined), DefaultError, Prisma.KitchenTicketItemCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.KitchenTicketItemCreateArgs, DefaultError, KitchenTicketItem, true>('KitchenTicketItem', 'POST', `${endpoint}/kitchenTicketItem/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.KitchenTicketItemCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.KitchenTicketItemCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, KitchenTicketItem, Prisma.KitchenTicketItemGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.KitchenTicketItemCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, KitchenTicketItem, Prisma.KitchenTicketItemGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyKitchenTicketItem(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.KitchenTicketItemCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.KitchenTicketItemCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('KitchenTicketItem', 'POST', `${endpoint}/kitchenTicketItem/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.KitchenTicketItemCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.KitchenTicketItemCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.KitchenTicketItemCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemFindManyArgs, TQueryFnData = Array<Prisma.KitchenTicketItemGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/findMany`, args, options, fetch);
}

export function useInfiniteFindManyKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemFindManyArgs, TQueryFnData = Array<Prisma.KitchenTicketItemGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/findMany`, args, options, fetch);
}

export function useSuspenseFindManyKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemFindManyArgs, TQueryFnData = Array<Prisma.KitchenTicketItemGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemFindManyArgs, TQueryFnData = Array<Prisma.KitchenTicketItemGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/findMany`, args, options, fetch);
}

export function useFindUniqueKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemFindUniqueArgs, TQueryFnData = Prisma.KitchenTicketItemGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemFindUniqueArgs, TQueryFnData = Prisma.KitchenTicketItemGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/findUnique`, args, options, fetch);
}

export function useFindFirstKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemFindFirstArgs, TQueryFnData = Prisma.KitchenTicketItemGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemFindFirstArgs, TQueryFnData = Prisma.KitchenTicketItemGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/findFirst`, args, options, fetch);
}

export function useUpdateKitchenTicketItem(options?: Omit<(UseMutationOptions<(KitchenTicketItem | undefined), DefaultError, Prisma.KitchenTicketItemUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.KitchenTicketItemUpdateArgs, DefaultError, KitchenTicketItem, true>('KitchenTicketItem', 'PUT', `${endpoint}/kitchenTicketItem/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.KitchenTicketItemUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.KitchenTicketItemUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, KitchenTicketItem, Prisma.KitchenTicketItemGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.KitchenTicketItemUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, KitchenTicketItem, Prisma.KitchenTicketItemGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyKitchenTicketItem(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.KitchenTicketItemUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.KitchenTicketItemUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('KitchenTicketItem', 'PUT', `${endpoint}/kitchenTicketItem/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.KitchenTicketItemUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.KitchenTicketItemUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.KitchenTicketItemUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertKitchenTicketItem(options?: Omit<(UseMutationOptions<(KitchenTicketItem | undefined), DefaultError, Prisma.KitchenTicketItemUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.KitchenTicketItemUpsertArgs, DefaultError, KitchenTicketItem, true>('KitchenTicketItem', 'POST', `${endpoint}/kitchenTicketItem/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.KitchenTicketItemUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.KitchenTicketItemUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, KitchenTicketItem, Prisma.KitchenTicketItemGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.KitchenTicketItemUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, KitchenTicketItem, Prisma.KitchenTicketItemGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteKitchenTicketItem(options?: Omit<(UseMutationOptions<(KitchenTicketItem | undefined), DefaultError, Prisma.KitchenTicketItemDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.KitchenTicketItemDeleteArgs, DefaultError, KitchenTicketItem, true>('KitchenTicketItem', 'DELETE', `${endpoint}/kitchenTicketItem/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.KitchenTicketItemDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.KitchenTicketItemDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, KitchenTicketItem, Prisma.KitchenTicketItemGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.KitchenTicketItemDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, KitchenTicketItem, Prisma.KitchenTicketItemGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyKitchenTicketItem(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.KitchenTicketItemDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.KitchenTicketItemDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('KitchenTicketItem', 'DELETE', `${endpoint}/kitchenTicketItem/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.KitchenTicketItemDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.KitchenTicketItemDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.KitchenTicketItemDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemAggregateArgs, TQueryFnData = Prisma.GetKitchenTicketItemAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemAggregateArgs, TQueryFnData = Prisma.GetKitchenTicketItemAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/aggregate`, args, options, fetch);
}

export function useGroupByKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.KitchenTicketItemGroupByArgs['orderBy'] } : { orderBy?: Prisma.KitchenTicketItemGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.KitchenTicketItemGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.KitchenTicketItemGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.KitchenTicketItemGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.KitchenTicketItemGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.KitchenTicketItemGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.KitchenTicketItemGroupByArgs['orderBy'] } : { orderBy?: Prisma.KitchenTicketItemGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.KitchenTicketItemGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.KitchenTicketItemGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.KitchenTicketItemGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.KitchenTicketItemGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.KitchenTicketItemGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/groupBy`, args, options, fetch);
}

export function useCountKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.KitchenTicketItemCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/count`, args, options, fetch);
}

export function useSuspenseCountKitchenTicketItem<TArgs extends Prisma.KitchenTicketItemCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.KitchenTicketItemCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.KitchenTicketItemCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/count`, args, options, fetch);
}
import type { KitchenTicketStatus } from './__types';

export function useCheckKitchenTicketItem<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; storeId?: string; ticketId?: string; orderItemId?: string; productId?: string; productNameSnapshot?: string; quantity?: number; notes?: string; status?: KitchenTicketStatus }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('KitchenTicketItem', `${endpoint}/kitchenTicketItem/check`, args, options, fetch);
}
