/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, OrderAuditLog } from "./__types";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateOrderAuditLog(options?: Omit<(UseMutationOptions<(OrderAuditLog | undefined), DefaultError, Prisma.OrderAuditLogCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderAuditLogCreateArgs, DefaultError, OrderAuditLog, true>('OrderAuditLog', 'POST', `${endpoint}/orderAuditLog/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderAuditLogCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderAuditLogCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OrderAuditLog, Prisma.OrderAuditLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderAuditLogCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OrderAuditLog, Prisma.OrderAuditLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyOrderAuditLog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderAuditLogCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderAuditLogCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('OrderAuditLog', 'POST', `${endpoint}/orderAuditLog/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderAuditLogCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderAuditLogCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderAuditLogCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyOrderAuditLog<TArgs extends Prisma.OrderAuditLogFindManyArgs, TQueryFnData = Array<Prisma.OrderAuditLogGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/findMany`, args, options, fetch);
}

export function useInfiniteFindManyOrderAuditLog<TArgs extends Prisma.OrderAuditLogFindManyArgs, TQueryFnData = Array<Prisma.OrderAuditLogGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/findMany`, args, options, fetch);
}

export function useSuspenseFindManyOrderAuditLog<TArgs extends Prisma.OrderAuditLogFindManyArgs, TQueryFnData = Array<Prisma.OrderAuditLogGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyOrderAuditLog<TArgs extends Prisma.OrderAuditLogFindManyArgs, TQueryFnData = Array<Prisma.OrderAuditLogGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/findMany`, args, options, fetch);
}

export function useFindUniqueOrderAuditLog<TArgs extends Prisma.OrderAuditLogFindUniqueArgs, TQueryFnData = Prisma.OrderAuditLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueOrderAuditLog<TArgs extends Prisma.OrderAuditLogFindUniqueArgs, TQueryFnData = Prisma.OrderAuditLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/findUnique`, args, options, fetch);
}

export function useFindFirstOrderAuditLog<TArgs extends Prisma.OrderAuditLogFindFirstArgs, TQueryFnData = Prisma.OrderAuditLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstOrderAuditLog<TArgs extends Prisma.OrderAuditLogFindFirstArgs, TQueryFnData = Prisma.OrderAuditLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/findFirst`, args, options, fetch);
}

export function useUpdateOrderAuditLog(options?: Omit<(UseMutationOptions<(OrderAuditLog | undefined), DefaultError, Prisma.OrderAuditLogUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderAuditLogUpdateArgs, DefaultError, OrderAuditLog, true>('OrderAuditLog', 'PUT', `${endpoint}/orderAuditLog/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderAuditLogUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderAuditLogUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OrderAuditLog, Prisma.OrderAuditLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderAuditLogUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OrderAuditLog, Prisma.OrderAuditLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyOrderAuditLog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderAuditLogUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderAuditLogUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('OrderAuditLog', 'PUT', `${endpoint}/orderAuditLog/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderAuditLogUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderAuditLogUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderAuditLogUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertOrderAuditLog(options?: Omit<(UseMutationOptions<(OrderAuditLog | undefined), DefaultError, Prisma.OrderAuditLogUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderAuditLogUpsertArgs, DefaultError, OrderAuditLog, true>('OrderAuditLog', 'POST', `${endpoint}/orderAuditLog/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderAuditLogUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderAuditLogUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OrderAuditLog, Prisma.OrderAuditLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderAuditLogUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OrderAuditLog, Prisma.OrderAuditLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteOrderAuditLog(options?: Omit<(UseMutationOptions<(OrderAuditLog | undefined), DefaultError, Prisma.OrderAuditLogDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderAuditLogDeleteArgs, DefaultError, OrderAuditLog, true>('OrderAuditLog', 'DELETE', `${endpoint}/orderAuditLog/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderAuditLogDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderAuditLogDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OrderAuditLog, Prisma.OrderAuditLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderAuditLogDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OrderAuditLog, Prisma.OrderAuditLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyOrderAuditLog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderAuditLogDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderAuditLogDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('OrderAuditLog', 'DELETE', `${endpoint}/orderAuditLog/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderAuditLogDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderAuditLogDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderAuditLogDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateOrderAuditLog<TArgs extends Prisma.OrderAuditLogAggregateArgs, TQueryFnData = Prisma.GetOrderAuditLogAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateOrderAuditLog<TArgs extends Prisma.OrderAuditLogAggregateArgs, TQueryFnData = Prisma.GetOrderAuditLogAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/aggregate`, args, options, fetch);
}

export function useGroupByOrderAuditLog<TArgs extends Prisma.OrderAuditLogGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.OrderAuditLogGroupByArgs['orderBy'] } : { orderBy?: Prisma.OrderAuditLogGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.OrderAuditLogGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.OrderAuditLogGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.OrderAuditLogGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.OrderAuditLogGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.OrderAuditLogGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByOrderAuditLog<TArgs extends Prisma.OrderAuditLogGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.OrderAuditLogGroupByArgs['orderBy'] } : { orderBy?: Prisma.OrderAuditLogGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.OrderAuditLogGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.OrderAuditLogGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.OrderAuditLogGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.OrderAuditLogGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.OrderAuditLogGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/groupBy`, args, options, fetch);
}

export function useCountOrderAuditLog<TArgs extends Prisma.OrderAuditLogCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.OrderAuditLogCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/count`, args, options, fetch);
}

export function useSuspenseCountOrderAuditLog<TArgs extends Prisma.OrderAuditLogCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.OrderAuditLogCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderAuditLogCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/count`, args, options, fetch);
}
import type { OrderAuditAction, OrderStatus } from './__types';

export function useCheckOrderAuditLog<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; storeId?: string; orderId?: string; action?: OrderAuditAction; fromStatus?: OrderStatus; toStatus?: OrderStatus; reason?: string; operatorId?: string; approvedById?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('OrderAuditLog', `${endpoint}/orderAuditLog/check`, args, options, fetch);
}
