/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, OrderPayment } from "./__types";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateOrderPayment(options?: Omit<(UseMutationOptions<(OrderPayment | undefined), DefaultError, Prisma.OrderPaymentCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderPaymentCreateArgs, DefaultError, OrderPayment, true>('OrderPayment', 'POST', `${endpoint}/orderPayment/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderPaymentCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderPaymentCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OrderPayment, Prisma.OrderPaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderPaymentCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OrderPayment, Prisma.OrderPaymentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyOrderPayment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderPaymentCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderPaymentCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('OrderPayment', 'POST', `${endpoint}/orderPayment/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderPaymentCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderPaymentCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderPaymentCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyOrderPayment<TArgs extends Prisma.OrderPaymentFindManyArgs, TQueryFnData = Array<Prisma.OrderPaymentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/findMany`, args, options, fetch);
}

export function useInfiniteFindManyOrderPayment<TArgs extends Prisma.OrderPaymentFindManyArgs, TQueryFnData = Array<Prisma.OrderPaymentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/findMany`, args, options, fetch);
}

export function useSuspenseFindManyOrderPayment<TArgs extends Prisma.OrderPaymentFindManyArgs, TQueryFnData = Array<Prisma.OrderPaymentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyOrderPayment<TArgs extends Prisma.OrderPaymentFindManyArgs, TQueryFnData = Array<Prisma.OrderPaymentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/findMany`, args, options, fetch);
}

export function useFindUniqueOrderPayment<TArgs extends Prisma.OrderPaymentFindUniqueArgs, TQueryFnData = Prisma.OrderPaymentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueOrderPayment<TArgs extends Prisma.OrderPaymentFindUniqueArgs, TQueryFnData = Prisma.OrderPaymentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/findUnique`, args, options, fetch);
}

export function useFindFirstOrderPayment<TArgs extends Prisma.OrderPaymentFindFirstArgs, TQueryFnData = Prisma.OrderPaymentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstOrderPayment<TArgs extends Prisma.OrderPaymentFindFirstArgs, TQueryFnData = Prisma.OrderPaymentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/findFirst`, args, options, fetch);
}

export function useUpdateOrderPayment(options?: Omit<(UseMutationOptions<(OrderPayment | undefined), DefaultError, Prisma.OrderPaymentUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderPaymentUpdateArgs, DefaultError, OrderPayment, true>('OrderPayment', 'PUT', `${endpoint}/orderPayment/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderPaymentUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderPaymentUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OrderPayment, Prisma.OrderPaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderPaymentUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OrderPayment, Prisma.OrderPaymentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyOrderPayment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderPaymentUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderPaymentUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('OrderPayment', 'PUT', `${endpoint}/orderPayment/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderPaymentUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderPaymentUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderPaymentUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertOrderPayment(options?: Omit<(UseMutationOptions<(OrderPayment | undefined), DefaultError, Prisma.OrderPaymentUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderPaymentUpsertArgs, DefaultError, OrderPayment, true>('OrderPayment', 'POST', `${endpoint}/orderPayment/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderPaymentUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderPaymentUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OrderPayment, Prisma.OrderPaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderPaymentUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OrderPayment, Prisma.OrderPaymentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteOrderPayment(options?: Omit<(UseMutationOptions<(OrderPayment | undefined), DefaultError, Prisma.OrderPaymentDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderPaymentDeleteArgs, DefaultError, OrderPayment, true>('OrderPayment', 'DELETE', `${endpoint}/orderPayment/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderPaymentDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderPaymentDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OrderPayment, Prisma.OrderPaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderPaymentDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OrderPayment, Prisma.OrderPaymentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyOrderPayment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderPaymentDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderPaymentDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('OrderPayment', 'DELETE', `${endpoint}/orderPayment/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderPaymentDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderPaymentDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderPaymentDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateOrderPayment<TArgs extends Prisma.OrderPaymentAggregateArgs, TQueryFnData = Prisma.GetOrderPaymentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateOrderPayment<TArgs extends Prisma.OrderPaymentAggregateArgs, TQueryFnData = Prisma.GetOrderPaymentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/aggregate`, args, options, fetch);
}

export function useGroupByOrderPayment<TArgs extends Prisma.OrderPaymentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.OrderPaymentGroupByArgs['orderBy'] } : { orderBy?: Prisma.OrderPaymentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.OrderPaymentGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.OrderPaymentGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.OrderPaymentGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.OrderPaymentGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.OrderPaymentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByOrderPayment<TArgs extends Prisma.OrderPaymentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.OrderPaymentGroupByArgs['orderBy'] } : { orderBy?: Prisma.OrderPaymentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.OrderPaymentGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.OrderPaymentGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.OrderPaymentGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.OrderPaymentGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.OrderPaymentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/groupBy`, args, options, fetch);
}

export function useCountOrderPayment<TArgs extends Prisma.OrderPaymentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.OrderPaymentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/count`, args, options, fetch);
}

export function useSuspenseCountOrderPayment<TArgs extends Prisma.OrderPaymentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.OrderPaymentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OrderPaymentCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OrderPayment', `${endpoint}/orderPayment/count`, args, options, fetch);
}
import type { PaymentMethod } from './__types';

export function useCheckOrderPayment<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; orderId?: string; method?: PaymentMethod }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('OrderPayment', `${endpoint}/orderPayment/check`, args, options, fetch);
}
