/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, PrinterRoute } from "./__types";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreatePrinterRoute(options?: Omit<(UseMutationOptions<(PrinterRoute | undefined), DefaultError, Prisma.PrinterRouteCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PrinterRouteCreateArgs, DefaultError, PrinterRoute, true>('PrinterRoute', 'POST', `${endpoint}/printerRoute/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PrinterRouteCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PrinterRouteCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PrinterRoute, Prisma.PrinterRouteGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PrinterRouteCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PrinterRoute, Prisma.PrinterRouteGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyPrinterRoute(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PrinterRouteCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PrinterRouteCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('PrinterRoute', 'POST', `${endpoint}/printerRoute/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PrinterRouteCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PrinterRouteCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PrinterRouteCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyPrinterRoute<TArgs extends Prisma.PrinterRouteFindManyArgs, TQueryFnData = Array<Prisma.PrinterRouteGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/findMany`, args, options, fetch);
}

export function useInfiniteFindManyPrinterRoute<TArgs extends Prisma.PrinterRouteFindManyArgs, TQueryFnData = Array<Prisma.PrinterRouteGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/findMany`, args, options, fetch);
}

export function useSuspenseFindManyPrinterRoute<TArgs extends Prisma.PrinterRouteFindManyArgs, TQueryFnData = Array<Prisma.PrinterRouteGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyPrinterRoute<TArgs extends Prisma.PrinterRouteFindManyArgs, TQueryFnData = Array<Prisma.PrinterRouteGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/findMany`, args, options, fetch);
}

export function useFindUniquePrinterRoute<TArgs extends Prisma.PrinterRouteFindUniqueArgs, TQueryFnData = Prisma.PrinterRouteGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniquePrinterRoute<TArgs extends Prisma.PrinterRouteFindUniqueArgs, TQueryFnData = Prisma.PrinterRouteGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/findUnique`, args, options, fetch);
}

export function useFindFirstPrinterRoute<TArgs extends Prisma.PrinterRouteFindFirstArgs, TQueryFnData = Prisma.PrinterRouteGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstPrinterRoute<TArgs extends Prisma.PrinterRouteFindFirstArgs, TQueryFnData = Prisma.PrinterRouteGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/findFirst`, args, options, fetch);
}

export function useUpdatePrinterRoute(options?: Omit<(UseMutationOptions<(PrinterRoute | undefined), DefaultError, Prisma.PrinterRouteUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PrinterRouteUpdateArgs, DefaultError, PrinterRoute, true>('PrinterRoute', 'PUT', `${endpoint}/printerRoute/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PrinterRouteUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PrinterRouteUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PrinterRoute, Prisma.PrinterRouteGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PrinterRouteUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PrinterRoute, Prisma.PrinterRouteGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyPrinterRoute(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PrinterRouteUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PrinterRouteUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('PrinterRoute', 'PUT', `${endpoint}/printerRoute/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PrinterRouteUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PrinterRouteUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PrinterRouteUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertPrinterRoute(options?: Omit<(UseMutationOptions<(PrinterRoute | undefined), DefaultError, Prisma.PrinterRouteUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PrinterRouteUpsertArgs, DefaultError, PrinterRoute, true>('PrinterRoute', 'POST', `${endpoint}/printerRoute/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PrinterRouteUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.PrinterRouteUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PrinterRoute, Prisma.PrinterRouteGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PrinterRouteUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PrinterRoute, Prisma.PrinterRouteGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeletePrinterRoute(options?: Omit<(UseMutationOptions<(PrinterRoute | undefined), DefaultError, Prisma.PrinterRouteDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PrinterRouteDeleteArgs, DefaultError, PrinterRoute, true>('PrinterRoute', 'DELETE', `${endpoint}/printerRoute/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PrinterRouteDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.PrinterRouteDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PrinterRoute, Prisma.PrinterRouteGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PrinterRouteDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PrinterRoute, Prisma.PrinterRouteGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyPrinterRoute(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PrinterRouteDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PrinterRouteDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('PrinterRoute', 'DELETE', `${endpoint}/printerRoute/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PrinterRouteDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PrinterRouteDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PrinterRouteDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregatePrinterRoute<TArgs extends Prisma.PrinterRouteAggregateArgs, TQueryFnData = Prisma.GetPrinterRouteAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/aggregate`, args, options, fetch);
}

export function useSuspenseAggregatePrinterRoute<TArgs extends Prisma.PrinterRouteAggregateArgs, TQueryFnData = Prisma.GetPrinterRouteAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/aggregate`, args, options, fetch);
}

export function useGroupByPrinterRoute<TArgs extends Prisma.PrinterRouteGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PrinterRouteGroupByArgs['orderBy'] } : { orderBy?: Prisma.PrinterRouteGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.PrinterRouteGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.PrinterRouteGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.PrinterRouteGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.PrinterRouteGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PrinterRouteGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByPrinterRoute<TArgs extends Prisma.PrinterRouteGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PrinterRouteGroupByArgs['orderBy'] } : { orderBy?: Prisma.PrinterRouteGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.PrinterRouteGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.PrinterRouteGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.PrinterRouteGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.PrinterRouteGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PrinterRouteGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/groupBy`, args, options, fetch);
}

export function useCountPrinterRoute<TArgs extends Prisma.PrinterRouteCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PrinterRouteCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/count`, args, options, fetch);
}

export function useSuspenseCountPrinterRoute<TArgs extends Prisma.PrinterRouteCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PrinterRouteCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PrinterRouteCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PrinterRoute', `${endpoint}/printerRoute/count`, args, options, fetch);
}
import type { PrinterRouteType, PrintDocumentType } from './__types';

export function useCheckPrinterRoute<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; storeId?: string; printerId?: string; routeType?: PrinterRouteType; targetId?: string; documentType?: PrintDocumentType }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('PrinterRoute', `${endpoint}/printerRoute/check`, args, options, fetch);
}
