/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, ProductModifierOption } from "./__types";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateProductModifierOption(options?: Omit<(UseMutationOptions<(ProductModifierOption | undefined), DefaultError, Prisma.ProductModifierOptionCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductModifierOptionCreateArgs, DefaultError, ProductModifierOption, true>('ProductModifierOption', 'POST', `${endpoint}/productModifierOption/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductModifierOptionCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductModifierOptionCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ProductModifierOption, Prisma.ProductModifierOptionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductModifierOptionCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ProductModifierOption, Prisma.ProductModifierOptionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyProductModifierOption(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductModifierOptionCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductModifierOptionCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ProductModifierOption', 'POST', `${endpoint}/productModifierOption/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductModifierOptionCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductModifierOptionCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductModifierOptionCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyProductModifierOption<TArgs extends Prisma.ProductModifierOptionFindManyArgs, TQueryFnData = Array<Prisma.ProductModifierOptionGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/findMany`, args, options, fetch);
}

export function useInfiniteFindManyProductModifierOption<TArgs extends Prisma.ProductModifierOptionFindManyArgs, TQueryFnData = Array<Prisma.ProductModifierOptionGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/findMany`, args, options, fetch);
}

export function useSuspenseFindManyProductModifierOption<TArgs extends Prisma.ProductModifierOptionFindManyArgs, TQueryFnData = Array<Prisma.ProductModifierOptionGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyProductModifierOption<TArgs extends Prisma.ProductModifierOptionFindManyArgs, TQueryFnData = Array<Prisma.ProductModifierOptionGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/findMany`, args, options, fetch);
}

export function useFindUniqueProductModifierOption<TArgs extends Prisma.ProductModifierOptionFindUniqueArgs, TQueryFnData = Prisma.ProductModifierOptionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueProductModifierOption<TArgs extends Prisma.ProductModifierOptionFindUniqueArgs, TQueryFnData = Prisma.ProductModifierOptionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/findUnique`, args, options, fetch);
}

export function useFindFirstProductModifierOption<TArgs extends Prisma.ProductModifierOptionFindFirstArgs, TQueryFnData = Prisma.ProductModifierOptionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstProductModifierOption<TArgs extends Prisma.ProductModifierOptionFindFirstArgs, TQueryFnData = Prisma.ProductModifierOptionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/findFirst`, args, options, fetch);
}

export function useUpdateProductModifierOption(options?: Omit<(UseMutationOptions<(ProductModifierOption | undefined), DefaultError, Prisma.ProductModifierOptionUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductModifierOptionUpdateArgs, DefaultError, ProductModifierOption, true>('ProductModifierOption', 'PUT', `${endpoint}/productModifierOption/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductModifierOptionUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductModifierOptionUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ProductModifierOption, Prisma.ProductModifierOptionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductModifierOptionUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ProductModifierOption, Prisma.ProductModifierOptionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyProductModifierOption(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductModifierOptionUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductModifierOptionUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ProductModifierOption', 'PUT', `${endpoint}/productModifierOption/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductModifierOptionUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductModifierOptionUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductModifierOptionUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertProductModifierOption(options?: Omit<(UseMutationOptions<(ProductModifierOption | undefined), DefaultError, Prisma.ProductModifierOptionUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductModifierOptionUpsertArgs, DefaultError, ProductModifierOption, true>('ProductModifierOption', 'POST', `${endpoint}/productModifierOption/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductModifierOptionUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductModifierOptionUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ProductModifierOption, Prisma.ProductModifierOptionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductModifierOptionUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ProductModifierOption, Prisma.ProductModifierOptionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteProductModifierOption(options?: Omit<(UseMutationOptions<(ProductModifierOption | undefined), DefaultError, Prisma.ProductModifierOptionDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductModifierOptionDeleteArgs, DefaultError, ProductModifierOption, true>('ProductModifierOption', 'DELETE', `${endpoint}/productModifierOption/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductModifierOptionDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductModifierOptionDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ProductModifierOption, Prisma.ProductModifierOptionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductModifierOptionDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ProductModifierOption, Prisma.ProductModifierOptionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyProductModifierOption(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductModifierOptionDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductModifierOptionDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ProductModifierOption', 'DELETE', `${endpoint}/productModifierOption/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductModifierOptionDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductModifierOptionDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductModifierOptionDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateProductModifierOption<TArgs extends Prisma.ProductModifierOptionAggregateArgs, TQueryFnData = Prisma.GetProductModifierOptionAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateProductModifierOption<TArgs extends Prisma.ProductModifierOptionAggregateArgs, TQueryFnData = Prisma.GetProductModifierOptionAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/aggregate`, args, options, fetch);
}

export function useGroupByProductModifierOption<TArgs extends Prisma.ProductModifierOptionGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ProductModifierOptionGroupByArgs['orderBy'] } : { orderBy?: Prisma.ProductModifierOptionGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ProductModifierOptionGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ProductModifierOptionGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ProductModifierOptionGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ProductModifierOptionGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ProductModifierOptionGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByProductModifierOption<TArgs extends Prisma.ProductModifierOptionGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ProductModifierOptionGroupByArgs['orderBy'] } : { orderBy?: Prisma.ProductModifierOptionGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ProductModifierOptionGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ProductModifierOptionGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ProductModifierOptionGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ProductModifierOptionGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ProductModifierOptionGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/groupBy`, args, options, fetch);
}

export function useCountProductModifierOption<TArgs extends Prisma.ProductModifierOptionCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ProductModifierOptionCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/count`, args, options, fetch);
}

export function useSuspenseCountProductModifierOption<TArgs extends Prisma.ProductModifierOptionCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ProductModifierOptionCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ProductModifierOptionCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ProductModifierOption', `${endpoint}/productModifierOption/count`, args, options, fetch);
}

export function useCheckProductModifierOption<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; groupId?: string; name?: string; displayOrder?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ProductModifierOption', `${endpoint}/productModifierOption/check`, args, options, fetch);
}
